version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    groups:
      minor-and-patch:
        update-types:
          - 'patch'
          - 'minor'
      eslint:
        patterns:
          - '@typescript-eslint/*'
          - 'eslint*'
      gatsby:
        patterns:
          - 'gatsby*'
      react:
        patterns:
          - '@types/react'
          - '@types/react-dom'
          - 'react'
          - 'react-dom'
      stylelint:
        patterns:
          - 'stylelint*'
      vite:
        patterns:
          - '@vitest/*'
          - 'vitest'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
