declare const styles: {
  readonly 'column--span-1': string;
  readonly 'column--span-2': string;
  readonly 'column--span-3': string;
  readonly 'column--span-4': string;
  readonly 'column--span-5': string;
  readonly 'column--span-6': string;
  readonly 'column--span-7': string;
  readonly 'column--span-8': string;
  readonly 'column--span-9': string;
  readonly 'column--span-10': string;
  readonly 'column--span-11': string;
  readonly 'column--span-12': string;
  readonly 'column--start-1': string;
  readonly 'column--start-2': string;
  readonly 'column--start-3': string;
  readonly 'column--start-4': string;
  readonly 'column--start-5': string;
  readonly 'column--start-6': string;
  readonly 'column--start-7': string;
  readonly 'column--start-8': string;
  readonly 'column--start-9': string;
  readonly 'column--start-10': string;
  readonly 'column--start-11': string;
  readonly 'column--start-12': string;
};
export = styles;
