declare const styles: {
  readonly columnSpan1: string;
  readonly columnSpan2: string;
  readonly columnSpan3: string;
  readonly columnSpan4: string;
  readonly columnSpan5: string;
  readonly columnSpan6: string;
  readonly columnSpan7: string;
  readonly columnSpan8: string;
  readonly columnSpan9: string;
  readonly columnSpan10: string;
  readonly columnSpan11: string;
  readonly columnSpan12: string;
  readonly columnStart1: string;
  readonly columnStart2: string;
  readonly columnStart3: string;
  readonly columnStart4: string;
  readonly columnStart5: string;
  readonly columnStart6: string;
  readonly columnStart7: string;
  readonly columnStart8: string;
  readonly columnStart9: string;
  readonly columnStart10: string;
  readonly columnStart11: string;
  readonly columnStart12: string;
};
export = styles;
