import { ABOUT, ACTING, CONTACT, GALLERY, IMPRINT, PRIVACY, THEATRE_PEDAGOGY } from './routes';

export const FOOTER = [PRIVACY, IMPRINT];

export const MAIN = [ABOUT, GALLERY, ACTING, THEATRE_PEDAGOGY, CONTACT];
