import { ABOUT, ACTING, DANCING, GALLERY, IMPRINT, PRIVACY, THEATRE_PEDAGOGY } from './routes';

export const FOOTER = [IMPRINT, PRIVACY];

export const MAIN = [ABOUT, ACTING, THEATRE_PEDAGOGY, DANCING, GALLERY];
